MySite/app/home/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from werkzeug.utils import secure_filename


class ContactForm(FlaskForm):
    name = StringField('Name')
    lastname = StringField('LastName')
    email = StringField('Email')

MySite/app/__init__.py
from flask import Flask

from flask_qrcode import QRcode  # For use to generate QR Codes


def create_application():
    app = Flask(__name__)

    # Initializations
    QRcode(app)

    # blueprint for non-auth parts of app
    from .home.routes import home as main_blueprint
    from .api.routes import api as api_blueprint

    # Register non Auth Blueprints
    app.register_blueprint(main_blueprint)
    app.register_blueprint(api_blueprint, url_prefix='/api')

    return app

MySite/app/api/routes.py
from flask import Blueprint, render_template, jsonify, request, send_file
from flask import current_app as app

import os
import hashlib

from .utils import check_valid_client, validate_client, qr_vcard


api = Blueprint('api', __name__)


@api.route('/')
def home():
    """ API Home Page """
    return render_template('api.html')


@api.route('/keygen')
def gen_api_key():
    """ Generate a new API key on reload """

    api_key = hashlib.sha256(os.urandom(32)).hexdigest()  # preferred
    api_key2 = os.urandom(16)

    return render_template('api-gen.html', key1=api_key, key2=api_key2)


@api.route('/qr', methods=['GET', 'POST'])
def generate_qr():
    """ QR Code Generator """

    if request.method == "POST":
        firstname = request.args.get('firstname')
        lastname = request.args.get('lastname')
        email = f"{firstname.lower()}.{lastname.lower()}@rsa.co.za"

        return jsonify(Email_address=email)

    return jsonify(response={"success": "Successfully Sent the data."})  # true when Get request


@api.route('/get_image', methods=['GET', 'POST'])
def get_image_from_get():
    """ Renders a image from url """

    I_UPLOAD_FOLDER = "static/site_img"

    if request.args.get('type') == '1':
        filename = "ok.gif"
    else:
        filename = "error.gif"

    # path = url_for('static', filename='site_img/')
    path2 = os.path.join(app.root_path, I_UPLOAD_FOLDER, filename)

    return send_file(path2, mimetype='image/gif', as_attachment=False)
    # return send_from_directory(path2, filename)


@api.route('/json-data', methods=['POST'])
def json_data():
    """
    returns formatted string from posted json data
    and also builds the email address
    """

    data = request.get_json()

    username = None
    surname = None
    mobile_phone = None
    job_title = None
    department = None
    business_unit = None
    domain = "@rsa.co.za"
    email = None

    if data:
        if 'UserName' in data:
            username = data['UserName']

        if 'Surname' in data:
            surname = data['Surname']

        if 'mobilePhone' in data:
            mobile_phone = data['mobilePhone']

        if 'JobTitle' in data:
            job_title = data['JobTitle']

        if 'Department' in data:
            department = data['Department']

        if 'Business unit' in data:
            business_unit = data['Business unit']

        email = f"{username}.{surname}{domain}"

    return f'''
               The Username value is: {username}
               The Surname value is: {surname}
               The Mobile Phone value is: {mobile_phone}
               The Job Title value is: {job_title}
               The Department value is: {department}
               The Business Unit value is: {business_unit}
               The email value is: {email}
               '''


@api.route('/json-example', methods=['POST'])
def json_example():
    """ returns formatted string from posted json data """

    request_json_data = request.get_json()

    language = None
    framework = None
    python_version = None
    example = None
    boolean_test = None

    if request_json_data:
        if 'language' in request_json_data:
            language = request_json_data['language']

        if 'framework' in request_json_data:
            framework = request_json_data['framework']

        if 'version_info' in request_json_data:
            if 'python' in request_json_data['version_info']:
                python_version = request_json_data['version_info']['python']

        if 'examples' in request_json_data:
            if (type(request_json_data['examples']) == list) and (len(request_json_data['examples']) > 0):
                example = request_json_data['examples'][0]

        if 'boolean_test' in request_json_data:
            boolean_test = request_json_data['boolean_test']

    return '''
               The language value is: {}
               The framework value is: {}
               The Python version is: {}
               The item at index 0 in the example list is: {}
               The boolean value is: {}'''.format(language, framework, python_version, example, boolean_test)


@api.route('/nandis-json', methods=['POST'])
def nandis():
    """ returns only email from posted json data """

    request_json_data = request.get_json()

    username = None
    surname = None
    mobile_phone = None
    job_title = None
    department = None
    business_unit = None
    domain = "@rsa.co.za"

    if request_json_data:
        if 'UserName' in request_json_data:
            username = request_json_data['UserName']

        if 'Surname' in request_json_data:
            surname = request_json_data['Surname']

        if 'mobilePhone' in request_json_data:
            mobile_phone = request_json_data['mobilePhone']

        if 'JobTitle' in request_json_data:
            job_title = request_json_data['JobTitle']

        if 'Department' in request_json_data:
            department = request_json_data['Department']

        if 'Business unit' in request_json_data:
            business_unit = request_json_data['Business unit']

        email = f"{username}.{surname}{domain}"

        return jsonify(
            mail=email)  # true when Get request


@api.route('/nandis-json-v2', methods=['POST'])
def nandis_v2():
    """ returns only email from posted json data working for RSA"""

    request_json_data = request.get_json()

    output = check_valid_client(request_json_data)

    return jsonify(output)


@api.route('/client-vcard-qr-v1', methods=['POST'])
def qr_client():
    """ Generate a qrcode for clients """

    data = request.get_json()
    validated_client = validate_client(data)

    if validated_client:
        # return jsonify(response={"success": "You will recieve your vcard QR Code."})  # true when Get requeststatus=200, "Your Vcard QR Code will be generated")
        qr = qr_vcard(data)
        return jsonify(qr)

    else:
        return jsonify("You are not allowed to generate qr codes")

MySite/app/home/routes.py
from flask import Blueprint, render_template

from flask import current_app as app

home = Blueprint('home', __name__)


@home.route('/')
def index():  # put application's code here
    return render_template('index.html')


@home.route('/skills')
def skills():
    return render_template('skills.html')

MySite/app/templates/api-gen.html
{% extends 'second-base.html' %}


<!-- Page title -->
{% block title %}

    <title>api Generator</title>

{% endblock %}


<!-- Features Section -->
{% block features %}

    <h6>Key1: {{ key1 }}</h6>
    <h6>Key2: {{ key2 }}</h6>

{% endblock %}

MySite/app/templates/api-output.html
{% extends 'second-base.html' %}

<!-- Page title -->
{% block title %}

    <title>nandis-json-v2</title>

{% endblock %}

<!-- Features Section -->
{% block features %}

    <!-- Skills section -->
    <div class="section-cv">

        <div class="row section-headers">

            <h1>nandis-json-v2</h1>

            <h5>{{ output }}</h5>

    </div>

{% endblock %}

MySite/app/templates/api.html
{% extends 'second-base.html' %}

<!-- Page title -->
{% block title %}

    <title>API</title>

{% endblock %}

<!-- Features Section -->
{% block features %}

    <!-- Skills section -->
    <div class="section-cv">
        <div class="row section-headers">

            <h1>API Page links</h1>

            <a class="nav-link" href={{ url_for("home.index") }}>Home</a>
            <br>
            <a class="nav-link" href={{ url_for("api.home") }}>API</a>
            <hr>

            <h2>How to use the API's</h2>

            <ul>
                <li><a href="http://127.0.0.1:5000/api/get_image?type=1">Get Img (GET)</a></li>
                <li><a href="http://127.0.0.1:5000/api/qr?firstname=Marius&lastname=Niehaus">Inline Json (Post)</a></li>
            </ul>

        </div>

    </div>

    <hr>

    <div class="section-cv">
        <div class="row section-headers">
            <h2>QR Code Examples</h2>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 qrcodes">
                <img src="{{ qrcode("https://tamato27.pythonanywhere.com", box_size=4, border=3, error_correction='H') }}">
                <img src="{{ qrcode("https://tamato27.pythonanywhere.com",box_size=4, border=3, error_correction='H', icon_img='site_img/icons/me-circle.png')  }}">
                <img src="{{ qrcode("https://tamato27.pythonanywhere.com", box_size=4, border=3,  error_correction='H', icon_img='site_img/icons/me-circle.png', back_color='ffff', fill_color='green') }}">
                <img src="{{ qrcode("https://tamato27.pythonanywhere.com", box_size=4, border=3,  error_correction='H', back_color='ffff', fill_color='red') }}">
            </div>
        </div>
    </div>


{% endblock %}

MySite/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

<!-- Links and css sources -->
{% include 'header.html' %}
<!-- Page Title -->
{% block title %}<title>Skills</title>{% endblock %}

</head>
<body>


<!-- Title Header -->
<section id="title">

    {% include 'title-section.html' %}

</section>


<!-- Features Section -->
<section id="features">

      <div class="container-fluid">

        {% block features %}{% endblock %}  {# Site pages contents #}

      </div>

</section>


<!-- Testimonials section -->
<section id="testimonials">

    {% block testimonial %}{% endblock %}

</section>


<!-- Press Section-->
<section id="press">

    {% block press %}{% endblock %}

</section>


<!-- Pricing Section-->
<section id="pricing">

    {% block pricing %}{% endblock %}

</section>


<!-- Call to Action Section -->
<section id="cta">

    {% block action %}{% endblock %}

</section>


<!-- Footer  Section-->
<footer id="footer">

    {% include 'footer.html' %}

{#    <p>© Copyright 2021 MN</p>#}

</footer>

</body>

</html>

MySite/app/templates/contact-form.html
 
{% block content %}
  <h2>Contact</h2>
  <form action="{{ url_for('contact') }}" method=post>
    {{ form.hidden_tag() }}
 
    {{ form.name.label }}
    {{ form.name }}
 
    {{ form.email.label }}
    {{ form.email }}
 
    {{ form.subject.label }}
    {{ form.subject }}
 
    {{ form.message.label }}
    {{ form.message }}
 
    {{ form.submit }}
  </form>
{% endblock %}

MySite/app/templates/footer.html
<section class="footer-section">
    <!-- Footer -->
    <footer class="white-section" id="footer">
        <img class="my-logo" src="{{ url_for('static', filename='site_img/icons/Logo-round.png') }}" width="60" height="60" color="red" alt="MN Logo">
        <div class="container-fluid">
            <i class="fb social-icon fab fa-facebook-f"></i>
            <i class="tw social-icon fab fa-twitter"></i>
            <i class="insta social-icon fab fa-instagram"></i>
            <i class="social-icon fas fa-envelope"></i>
            <p>© Copyright {{ year }} MN</p>
        </div>
    </footer>
</section>

MySite/app/templates/header.html
    <meta charset="utf-8">

    <!-- Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cantarell:ital,wght@1,700&family=Montserrat:wght@100;900&display=swap" rel="stylesheet">

    <!-- Google Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- CSS Stylesheets Bootsrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Custom Css Styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/skill_styles.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='site_img/icons/favicon-32x32.png')}}" type="image/">

    <!-- Bootstrap Scripts-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Font Awesome-->
    <script src="https://kit.fontawesome.com/f37fe10177.js" crossorigin="anonymous"></script>

MySite/app/templates/index.html
{% extends 'base.html' %}

{% block title %}

    <title>Portfolio</title>

{% endblock %}


<!-- Features Section -->
{% block features %}

    <h3 class="feature-titles">It's all about me.</h3>
    <br>
    <p>
        For a change this is all about me....Just Kidding in a way 🤓.
        To Start off I have made this Site available to everyone to show off my abilities and also my Professional side,
        You can view my skills and interactive resume, right on this site.

        I have some free projects that I have built also available here and some not so free, So please feel free to look around.
        <br><br>
        PS Thanks for the visit 👀.
    </p>
    <br><br>

    <h3 class="feature-titles">Site info</h3>
    <br>
    <p>
        It is all about the details...<br>
        I have put together this site to showcase my skills, but enough about that, Lets get Technical.
        Below Technologies and languages was used to write this site.
        And I will mention all the links and sources that i used.
    </p>
    <br><br>

{#    <div class="container-fluid logo-container">#}

        <img src="https://www.python.org/static/community_logos/python-logo.png" width="165" height="64" alt="Python Logo" title="Python Logo">
        <img src="https://flask.palletsprojects.com/en/2.0.x/_images/flask-logo.png" width="165" height="64" alt="Flask Logo" title="Flask Logo">
        <img src="https://jinja.palletsprojects.com/en/3.0.x/_images/jinja-logo.png" width="165" height="64" alt="Css Logo" title="Jinja Logo">
        <img src="https://www.w3.org/html/logo/badge/html5-badge-h-css3-semantics.png" width="165" height="64" alt="HTML5 Powered with CSS3 / Styling, and Semantics" title="HTML5 Powered with CSS3 / Styling, and Semantics">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/CSS3_logo_and_wordmark.svg/120px-CSS3_logo_and_wordmark.svg.png" width="60" height="64" alt="Css Logo" title="Css Logo">

{#    </div>#}
    <br><br>


{% endblock %}


{#<!-- Testimonials section -->#}
{#{% block testimonial %}#}
{##}
{#    <div class="container-fluid">#}
{##}
{#        <h3 class="feature-titles">I will add more data/info as my "Fan Base" grows. 🤭</h3>#}
{#        <em>by, Marius Niehaus.</em>#}
{##}
{#    </div>#}
{##}
{#    <!-- <h2 class="testimonial-text">My dog used to be so lonely, but with TinDog's help, they've found the love of their life. I think.</h2>#}
{#    <img class="testimonial-image" src="images/lady-img.jpg" alt="lady-profile">#}
{#    <em>Beverly, Illinois</em> -->#}
{##}
{#{% endblock %}#}
{##}
{##}
{#<!-- Press Section-->#}
{#{% block press %}#}
{##}
{#        <img src="images/techcrunch.png" alt="tc-logo">#}
{#        <img src="images/tnw.png" alt="tnw-logo">#}
{#        <img src="images/bizinsider.png" alt="biz-insider-logo">#}
{#        <img src="images/mashable.png" alt="mashable-logo">#}
{##}
{#{% endblock %}#}
{##}
{##}
{#<!-- Pricing Section-->#}
{#{% block pricing %}#}
{##}
{#    <h2>For The non free items</h2>#}
{#    <p>Simple and affordable price plans.</p>#}
{##}
{#    <h3>Thingies</h3>#}
{#    <h2>Free</h2>#}
{#    <p>5 Matches Per Day</p>#}
{#    <p>10 Messages Per Day</p>#}
{#    <p>Unlimited App Usage</p>#}
{#    <button type="button">Sign Up</button>#}
{##}
{#    <h3>Thingies again</h3>#}
{#    <h2>$49 / mo</h2>#}
{#    <p>Unlimited Matches</p>#}
{#    <p>Unlimited Messages</p>#}
{#    <p>Unlimited App Usage</p>#}
{#    <button type="button">Sign Up</button>#}
{##}
{#    <h3>Another Thingie</h3>#}
{#    <h2>$99 / mo</h2>#}
{#    <p>Pirority Listing</p>#}
{#    <p>Unlimited Matches</p>#}
{#    <p>Unlimited Messages</p>#}
{#    <p>Unlimited App Usage</p>#}
{#    <button type="button">Sign Up</button>#}
{##}
{#{% endblock %}#}
{##}
{##}
{#<!-- Call to Action Section -->#}
{#{% block action %}#}
{##}
{#    <h3>Find the True Love of Your Things's Life Today.</h3>#}
{#    <button type="button">Download</button>#}
{#    <button type="button">Download</button>#}
{##}
{#{% endblock %}#}

MySite/app/templates/second-base.html
<!DOCTYPE html>
<html lang="en">

<head>

<!-- Links and css sources -->
{% include 'header.html' %}
<!-- Page Title -->
{% block title %}<title>Skills</title>{% endblock %}

</head>
<body>


<!-- Title Header -->
<section id="title">

{% include 'small-title.html' %}

</section>


<!-- Features Section -->
<section id="features">

    <div class="container-fluid">
        {% block features %}{% endblock %}  {# Site pages contents #}
    </div>

</section>


<!-- Testimonials section -->
<section id="testimonials">

    {% block testimonials %}{% endblock %}

</section>


<!-- Press Section-->
<section id="press">

    {% block press %}{% endblock %}

</section>


<!-- Pricing Section-->
<section id="pricing">

    {% block pricing %}{% endblock %}

</section>


<!-- Call to Action Section -->
<section id="cta">

    {% block action %}{% endblock %}

</section>


<!-- Footer  Section-->
<footer id="footer">

    {% include 'footer.html' %}

{#    <p>© Copyright 2021 MN</p>#}

</footer>

</body>

</html>

MySite/app/templates/small-title.html
<div class="container-fluid">

    {#  Navbar bootstrap  #}
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid brand-nav">
                <a class="navbar-brand" href="">
                    <img class="title-image" src="{{ url_for('static', filename='site_img/icons/me-circle.png') }}" alt="marius profile picture"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href={{ url_for("home.index") }}>me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href={{ url_for("api.home") }}>API's</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Free</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Chat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for("home.skills") }}">Skills</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Snap</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

</div>

MySite/app/templates/title-section.html
<div class="container-fluid">

        {#  Navbar bootstrap  #}
        <nav class="navbar navbar-expand-sm navbar-dark">
            <div class="container-fluid brand-nav">
                <a class="navbar-brand" href="">
                <img class="title-image" src="{{ url_for('static', filename='site_img/icons/me-circle.png') }}" alt="marius profile picture"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href={{ url_for("home.index") }}>me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href={{ url_for("api.home") }}>API's</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Free</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Chat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Skills</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Snap</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

        <!-- Title -->
        <div class="row">

            <div class="col-lg-6">

                <div id="text-logo">
                    <div class="box-color-letter">
                        <h1>M</h1>
                    </div>

                    <div class="box-non-color-letter">
                        <h1>arius</h1>
                    </div>

                    <div class="box-color-letter">
                        <h1>N</h1>
                    </div>

                    <div class="box-non-color-letter">
                        <h1>iehaus</h1>
                    </div>

                </div>

                <h3>my</h3>
                <h2 class="portfolio-txt">Portfolio</h2>

            </div>

            <div class="col-lg-6">
                <span class="material-icons">fingerprint</span>
                <p class="title-text">An Aspiring Fullstack Developer & <br>Professional Network Engineer</p>
            </div>

        </div>

        <div class="row">
            <div class="col-lg-6">

                {# moving clouds #}
                <div id="clouds">
                <div class="cloud x1"></div>
                <!-- Time for multiple clouds to dance around -->
                <div class="cloud x2"></div>
{#                <div class="cloud x3"></div>#}
{#                <div class="cloud x4"></div>#}
{#                <div class="cloud x5"></div>#}
                </div>

            </div>
        </div>

    </div>